[package]
name = "spurilo"
version = "0.1.0"
authors = ["Cédric Eberhardt <hello+code@cedeber.fr>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
clap = "3.0.0-beta.5"
console = "0.15.0"
geo = "0.18.0"
gpx = "0.8.5"